Controllers/AnalisiController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LaboratorioMarn.Controllers
{
    public class AnalisiController : Controller
    {
        private MARNEntities db = new MARNEntities();

        public ActionResult Index()
        {
            return View(db.ANALISIS.ToList());
        }

        public ActionResult Create()
        {
            List<AREA> areas = db.AREAs.ToList();

            IEnumerable<SelectListItem> areasList =
            from area in areas
            select new SelectListItem
            {
                Value = area.id_area.ToString(),
                Text = area.nombre_area
            };

            ViewBag.AreasSelection = areasList;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ANALISI analisis)
        {
            if (ModelState.IsValid)
            {
                analisis.formula = "formula";

                ANALISI lastAnalisis = db.ANALISIS.OrderByDescending(a => a.id_analisis).First();

                analisis.id_analisis = lastAnalisis.id_analisis + 1;

                db.ANALISIS.Add(analisis);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(analisis);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ANALISI analisis = db.ANALISIS.Find(id);
            if (analisis == null)
            {
                return HttpNotFound();
            }

            List<AREA> areas = db.AREAs.ToList();

            IEnumerable<SelectListItem> areasList =
            from area in areas
            select new SelectListItem
            {
                Value = area.id_area.ToString(),
                Text = area.nombre_area
            };

            foreach (SelectListItem item in areasList)
            {
                if (item.Text.Equals(analisis.AREA.nombre_area))
                {
                    item.Selected = true;
                }
            }

            ViewBag.AreasSelection = areasList;

            return View(analisis);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ANALISI analisis)
        {
            if (ModelState.IsValid)
            {
                ANALISI analisisOriginal = db.ANALISIS.Find(analisis.id_analisis);
                analisisOriginal.id_area = analisis.id_area;
                analisisOriginal.metodo = analisis.metodo;
                analisisOriginal.nombre = analisis.nombre;
                analisisOriginal.unidades = analisis.unidades;
                analisisOriginal.incertezas = analisis.incertezas;
                analisisOriginal.limites = analisis.limites;
                analisisOriginal.costo = analisis.costo;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(analisis);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ANALISI analisis = db.ANALISIS.Find(id);
            if (analisis == null)
            {
                return HttpNotFound();
            }
            return View(analisis);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                ANALISI analisis = db.ANALISIS.Find(id);
                db.ANALISIS.Remove(analisis);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                TempData["msjError"] = "No se pudo eliminar el análisis";
                return RedirectToAction("Delete");
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/MuestraController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LaboratorioMarn.Controllers
{
    public class MuestraController : Controller
    {
        private MARNEntities db = new MARNEntities();

        // GET: MUESTRA_s
        public ActionResult Index()
        {
            return View(db.MUESTRAs.ToList());
        }

        // GET: MUESTRA_s/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MUESTRA mUESTRA = db.MUESTRAs.Find(id);
            if (mUESTRA == null)
            {
                return HttpNotFound();
            }
            return View(mUESTRA);
        }

        // GET: MUESTRA_s/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MUESTRA_s/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_muestra,nombre_muestra,expresado")] MUESTRA muestra)
        {
            //db.MUESTRAs.Select(i => i.id_muestra).Max().ToString();
            if (ModelState.IsValid)
            {
                muestra.id_muestra = int.Parse(db.MUESTRAs.Select(i => i.id_muestra).Max().ToString()) + 1;
                db.MUESTRAs.Add(muestra);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(muestra);
        }

        // GET: MUESTRA_s/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MUESTRA mUESTRA = db.MUESTRAs.Find(id);
            if (mUESTRA == null)
            {
                return HttpNotFound();
            }
            return View(mUESTRA);
        }

        // POST: MUESTRA_s/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_muestra,nombre_muestra,expresado")] MUESTRA mUESTRA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mUESTRA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mUESTRA);
        }

        // GET: MUESTRA_s/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MUESTRA mUESTRA = db.MUESTRAs.Find(id);
            if (mUESTRA == null)
            {
                return HttpNotFound();
            }
            return View(mUESTRA);
        }

        // POST: MUESTRA_s/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MUESTRA mUESTRA = db.MUESTRAs.Find(id);
            db.MUESTRAs.Remove(mUESTRA);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Calidad de Agua</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=calibri">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/font-awesome.min.css")" rel="stylesheet" type="text/css" />
    @RenderSection("Styles", required: false)

    <style>
        body {
          font-family: 'calibri', serif;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/"><img src="~/Images/marn solo letra.png" style="max-height: 50px; margin-top: 5px" class="img-responsive" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Inicio", "Index", "Home")
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                            Solicitud <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Solicitudes", "Index", "GrupoSolicitud")</li>
                            <li>@Html.ActionLink("Nueva Solicitud", "Create", "GrupoSolicitud")</li>
                            <li>@Html.ActionLink("Muestras", "Index", "Solicitud")</li>
                        </ul>
                    </li>
                    
                    <li >
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                            Reportes <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Actividad", "Reporte", "ReportesSolicitud")</li>
                            <li>@Html.ActionLink("Trabajo y costos", "TrabajoCosto", "ReportesSolicitud")</li>
                        </ul>
                        
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                            Inventario <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Reactivos", "Index", "Reactivo")</li>
                            <li>@Html.ActionLink("Productos en Bodega", "Index", "Producto")</li>
                            <li>@Html.ActionLink("Detalle Salidas", "ReporteSalida", "Producto")</li>
                            <li>@Html.ActionLink("Reporte de uso", "ReporteUso", "Producto")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                            Otros <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Solicitantes", "Index", "Solicitante")</li>
                            <li>@Html.ActionLink("Sitios Muestreo", "Index", "SitioMuestreo")</li>
                            <li>@Html.ActionLink("Analisis", "Index", "Analisi")</li>
                            <li>@Html.ActionLink("Parametros Muestra", "Index", "Muestra")</li>
                            <li>@Html.ActionLink("Empleados de Campo", "Index", "EmpleadoCampo")</li>
                        </ul>
                    </li>
                    <li>
                        @Html.ActionLink("Usuarios", "Index", "Admin")
                    </li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Laboratorio Calidad de Agua MARN</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">

        var countNotifications = function () {
            $.ajax({
                url: "@Url.Action("GetUnreadCount", "Notificacion")",
                type: "POST",
                success: function (json)
                {
                    $("#countNotifications").text(json.count);
                }
            });
        };

        $(function () {
            // navbar notification popups
            $(".notification-dropdown").each(function (index, el) {
                var $el = $(el);
                var $dialog = $el.find(".pop-dialog");
                var $trigger = $el.find(".trigger");

                $dialog.click(function (e) {
                    e.stopPropagation()
                });
                $dialog.find(".close-icon").click(function (e) {
                    e.preventDefault();
                    $dialog.removeClass("is-visible");
                    $trigger.removeClass("active");
                });
                $("body").click(function () {
                    $dialog.removeClass("is-visible");
                    $trigger.removeClass("active");
                });

                $trigger.click(function (e) {
                    e.preventDefault();
                    e.stopPropagation();

                    // hide all other pop-dialogs
                    $(".notification-dropdown .pop-dialog").removeClass("is-visible");
                    $(".notification-dropdown .trigger").removeClass("active")

                    $dialog.toggleClass("is-visible");
                    if ($dialog.hasClass("is-visible")) {
                        $(this).addClass("active");
                    } else {
                        $(this).removeClass("active");
                    }
                });
            });

            $("#verNotificaciones").click(function () {
                $.ajax({
                    url: "@Url.Action("GetLast", "Notificacion", new { number = 5 }, null)",
                    success: function (html) {
                        $("#mensajesNotificaciones").html(html);
                    }
                });
            });

            countNotifications();

            setInterval(countNotifications, 180000);
        });
    </script>
</body>
</html>

Views/Shared/_LayoutAnalista.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Calidad de Agua</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=calibri">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Styles", required: false)

    <style>
        body {
            font-family: 'calibri', serif;
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/Analista"><img src="~/Images/marn solo letra.png" style="max-height: 50px; margin-top: 5px" class="img-responsive" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Analista")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                            Inventario <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Inventario Bodega", "Index", "Producto")</li>
                            <li>@Html.ActionLink("Inventario Local", "inventarioLocal", "Producto")</li>
                            <li>@Html.ActionLink("Nueva Salida", "SeleccionSalida", "Producto")</li>
                            <li>@Html.ActionLink("Detalle Salidas", "ReporteSalida", "Producto")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Laboratorio Calidad de Agua MARN</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">

        var countNotifications = function () {
            $.ajax({
                url: "@Url.Action("GetUnreadCount", "Notificacion")",
                type: "POST",
                success: function (json)
                {
                    $("#countNotifications").text(json.count);
                }
            });
        };

        $(function () {
            // navbar notification popups
            $(".notification-dropdown").each(function (index, el) {
                var $el = $(el);
                var $dialog = $el.find(".pop-dialog");
                var $trigger = $el.find(".trigger");

                $dialog.click(function (e) {
                    e.stopPropagation()
                });
                $dialog.find(".close-icon").click(function (e) {
                    e.preventDefault();
                    $dialog.removeClass("is-visible");
                    $trigger.removeClass("active");
                });
                $("body").click(function () {
                    $dialog.removeClass("is-visible");
                    $trigger.removeClass("active");
                });

                $trigger.click(function (e) {
                    e.preventDefault();
                    e.stopPropagation();

                    // hide all other pop-dialogs
                    $(".notification-dropdown .pop-dialog").removeClass("is-visible");
                    $(".notification-dropdown .trigger").removeClass("active")

                    $dialog.toggleClass("is-visible");
                    if ($dialog.hasClass("is-visible")) {
                        $(this).addClass("active");
                    } else {
                        $(this).removeClass("active");
                    }
                });
            });

            $("#verNotificaciones").click(function () {
                $.ajax({
                    url: "@Url.Action("GetLast", "Notificacion", new { number = 5 }, null)",
                    success: function (html) {
                        $("#mensajesNotificaciones").html(html);
                    }
                });
            });

            countNotifications();

            setInterval(countNotifications, 180000);
        });
    </script>
</body>
</html>

Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Calidad de Agua</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=calibri">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Styles", required: false)
    <link href="@Url.Content("~/Content/font-awesome.min.css")" rel="stylesheet" type="text/css" />

    <style>
        body {
            font-family: 'calibri', serif;
        }
    </style>

</head>
<body>
    
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Laboratorio Calidad de Agua MARN</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>