Controllers/ReporteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LaboratorioMarn.Models;
using System.IO;
using Newtonsoft.Json;

using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using LaboratorioMarn.Infrastructure;
using LaboratorioMarn.Classes;

namespace LaboratorioMarn.Controllers
{
    public class ReporteController : Controller
    {
        MARNEntities db = new MARNEntities();
        // GET: Reporte

        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }

        private EMPLEADO empleado()
        {
            var username = User.Identity.GetUserName();
            AppUser user = UserManager.FindByName(username);
            return db.EMPLEADOes.First(e => e.id_aspnet_user == user.Id);
        }

        [HttpGet]
        public ActionResult Create(int idAnalisisEmpleado)
        {
            ANALISIS_EMPLEADO analisisEmpleado = db.ANALISIS_EMPLEADO.Find(idAnalisisEmpleado);
            ViewBag.AnalisisEmpleado = analisisEmpleado;

            var unidades = new SelectList(
                db.UNIDADs.Select(u => u.nombre).Distinct().ToList());

            ViewBag.Unidades = unidades;

            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(int idAnalisisEmpleado, REPORTE reporte)
        {
            object result;
            try
            {
                if (!true) { 
                    throw new Exception();
                }
                
                ANALISIS_EMPLEADO analisisEmpleado = db.ANALISIS_EMPLEADO.Find(idAnalisisEmpleado);
                
                reporte.id_analisis_empleado = analisisEmpleado.id_analisis_empleado;
                db.REPORTEs.Add(reporte);

                db.SaveChanges();
                
                result = new { valid = true };
            }
            catch(Exception e) {
                result = new { valid = false, msg = "Favor verifique los datos"};
            }
            return Json(result);
        }

        [HttpPost]
        public ActionResult Get(int procesoId)
        {
            PROCESO_ANALISTA procesoAnalista = db.PROCESO_ANALISTA.Find(procesoId);
            EMPLEADO empleado = procesoAnalista.EMPLEADO;

            IEnumerable<REPORTE> reportes = db.REPORTEs.Where(r =>
                r.ANALISIS_EMPLEADO.DETALLE_SOLICITUD.SOLICITUD.id_solicitud == procesoAnalista.SOLICITUD.id_solicitud &&
                r.ANALISIS_EMPLEADO.EMPLEADO.id_empleado == empleado.id_empleado
                ).ToList();

            ViewBag.empleado = empleado;
            ViewBag.procesoAnalista = procesoAnalista;

            return PartialView(reportes);
        }

        [HttpGet]
        public ActionResult Editar(int idReporte)
        {

            //REPORTE reporte = detalle.ANALISIS_EMPLEADO.First().REPORTEs.First();
            REPORTE reporte = db.REPORTEs.Find(idReporte);
            ViewBag.Reporte = reporte;
            DETALLE_SOLICITUD detalle = db.DETALLE_SOLICITUD.Find(reporte.ANALISIS_EMPLEADO.id_detalle_solicitud);
            ViewBag.DetalleSol = detalle;
            return PartialView(reporte);
        }


        [HttpPost]
        public ActionResult Editar(int idReporte, REPORTE postReporte)
        {
            object result;
            REPORTE reporteF = db.REPORTEs.Find(idReporte);

            db.Entry(reporteF).CurrentValues.SetValues(postReporte);

            db.SaveChanges();
            result = new { valid = true };

            return Json(result);

        }

        [HttpPost]
        [Authorize(Roles = "Analista")]
        public ActionResult EnviarResultado(int idSolicitud)
        {
            object result;

            EMPLEADO empleado = this.empleado();

            SOLICITUD solicitud = db.SOLICITUDs.Find(idSolicitud);

            PROCESO_ANALISTA procesoAnalista = db.PROCESO_ANALISTA.Single(pa => pa.empleado_id == empleado.id_empleado && pa.solicitud_id == solicitud.id_solicitud);

            procesoAnalista.fecha_fin = DateTime.Now;
            procesoAnalista.id_estado_proceso_analista = 3;
            db.SaveChanges();

            var reportesCompletos = true;
            foreach (PROCESO_ANALISTA procesosAnalista in solicitud.PROCESO_ANALISTA)
            {
                if (procesosAnalista.id_estado_proceso_analista != 3)
                {
                    reportesCompletos = false;
                }
            }

            // enviar notificacion
            Notificacion notificacion = new Notificacion(empleado.id_empleado, "Analisis de solicitud " + solicitud.no_referencia + " finalizados.", "Se finalizaron los analisis y ingresaron los resultados.", Url.Action("Detalle", "Solicitud", new { id = solicitud.id_solicitud }));
            notificacion.setReceptor();
            notificacion.send();

            if (reportesCompletos)
            {
                solicitud.id_estado_proceso = 4;
            }

            db.SaveChanges();

            if (reportesCompletos)
            {
                // enviar notificacion
                Notificacion notificacionCompleto = new Notificacion(empleado.id_empleado, "Reportes de solicitud " + solicitud.no_referencia + " finalizados.", "Se finalizaron todos los reportes y fueron enviados.", Url.Action("Detalle", "Solicitud", new { id = solicitud.id_solicitud }));
                notificacionCompleto.setReceptor();
                notificacionCompleto.send();
            }

            result = new { valid = true };
            return Json(result);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Revisar(int procesoId, string accion)
        {
            Object result;

            PROCESO_ANALISTA procesoAnalista = db.PROCESO_ANALISTA.Find(procesoId);
            SOLICITUD solicitud = procesoAnalista.SOLICITUD;

            try
            {
                if (accion == "aprobar")
                {
                    // si es diferente de reportado
                    if (procesoAnalista.id_estado_proceso_analista != 3)
                    {
                        throw new Exception("No es posible aprobar los resultado por el estado del proceso");
                    }

                    procesoAnalista.id_estado_proceso_analista = 4; // finalizado
                    db.SaveChanges();

                    bool todosFinalizados = true;
                    foreach (PROCESO_ANALISTA procesoAnalistaSolicitud in solicitud.PROCESO_ANALISTA.ToList())
                    { 
                        // si es diferente de finalizado y cerrado
                        if (procesoAnalistaSolicitud.id_estado_proceso_analista != 4 && procesoAnalistaSolicitud.id_estado_proceso_analista != 6)
                        {
                            todosFinalizados = false;
                        }
                    }

                    // si todos los procesos estan finalizados
                    if (todosFinalizados)
                    {
                        solicitud.id_estado_proceso = 4; // reportes completos
                        solicitud.id_estado = 3; // finalizado
                        solicitud.fecha_finalizacion = DateTime.Now;
                    }
        
                    db.SaveChanges();

                    EMPLEADO empleadoAnalista = db.EMPLEADOes.Find(procesoAnalista.EMPLEADO.id_empleado);
                    EMPLEADO empleado = this.empleado();

                    // enviar notificacion
                    Notificacion notificacion = new Notificacion(empleado.id_empleado, "Los resultados para solicitud " + solicitud.no_referencia + " fueron aprobados.", "Aprobados", Url.Action("Administrar", "Analisis", new { idSolicitud = solicitud.id_solicitud }));
                    notificacion.setReceptor(empleadoAnalista.id_empleado);
                    notificacion.send();

                    var msg = "El reporte de " + procesoAnalista.EMPLEADO.nombre_empleado + " se aprobo con exito.";
                    if (todosFinalizados)
                    {
                        msg += " El proceso ha finalizado, ahora puede generar un informe con todos los resultados";
                    }

                    result = new { valid = true, msg = msg };
                }
                else 
                { 
                    // finalizado y generado
                    if (procesoAnalista.id_estado_proceso_analista == 4 && procesoAnalista.SOLICITUD.informe_generado == 1)
                    {
                        throw new Exception ("El informe ya fue generado, para modificar los resultados debe de estar en un estado de 'Correccion'");
                    }

                    if (solicitud.id_estado_proceso == 6)
                    {
                        procesoAnalista.id_estado_proceso_analista = 5; // estado correccion
                    }
                    else
                    {
                        procesoAnalista.id_estado_proceso_analista = 2; // estado iniciado
                    }
                    procesoAnalista.fecha_fin = null;

                    // si el estado del proceso es reportes completos entonces set a iniciado
                    if (solicitud.id_estado_proceso == 4)
                    {
                        solicitud.id_estado_proceso = 3;
                    }

                    // si es estado de la solicitud es finalizada entonces set a proceso
                    if (solicitud.id_estado == 3)
                    {
                        solicitud.id_estado = 2;
                    }

                    db.SaveChanges();

                    EMPLEADO empleadoAnalista = db.EMPLEADOes.Find(procesoAnalista.EMPLEADO.id_empleado);
                    EMPLEADO empleado = this.empleado();

                    // enviar notificacion

Views/Reporte/Create.cshtml
@model LaboratorioMarn.REPORTE
@{
    ANALISIS_EMPLEADO analisisEmpleado = ViewBag.AnalisisEmpleado;
    ANALISI analisis = analisisEmpleado.DETALLE_SOLICITUD.ANALISI;
}
<div class="row">
    <div class="col-sm-12">
        @using (Html.BeginForm("Create", "Reporte", FormMethod.Post, htmlAttributes: new { @id = "formularioIngresoReporte", @class = "form-horizontal" }))
        {
            <input type="hidden" name="idAnalisisEmpleado" value="@analisisEmpleado.id_analisis_empleado" />
            @Html.AntiForgeryToken()

            <script type="text/javascript">
                function sumar() {
                    var resultado = document.getElementById('resultado').value;
                    var incerteza = document.getElementById('incerteza').value;

                    incerteza *= resultado;
                    document.getElementById('incerteza').value = incerteza;
                }

            </script>
            <div class="form-group">
                <label class="control-label col-md-4" for="resultado">Análisis: </label>
                <label class="control-label col-md-7" style="text-align: center" for="resultado">@analisis.nombre</label>
            </div>
            <div class="form-group">
                <label class="control-label col-md-4" for="resultado">Resultado: </label>
                <div class="col-md-7">
                    <input type="text" name="resultado" id="resultado" onchange="sumar()" class="form-control" />
                    @Html.ValidationMessageFor(model => model.resultado, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @if (analisis.id_area == 4)
                {
                    <label class="control-label col-md-4" for="resultado">Precisión: </label>
                }
                else
                {
                    <label class="control-label col-md-4" for="resultado">Incerteza: </label>
                }
                <div class="col-md-7">

                    <input type="text" name="incerteza" id="incerteza" value="@analisis.incertezas" class="form-control" />
                    @Html.ValidationMessageFor(model => model.unidades, "", new { @class = "text-danger" })
                    @*@Html.EditorFor(model => model.incerteza, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.incerteza, "", new { @class = "text-danger" })*@
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-4" for="resultado">Unidades: </label>
                <div class="col-md-7">
                    <input type="text" name="unidades" id="unidades" value="@analisis.unidades" class="form-control" />
                    @Html.ValidationMessageFor(model => model.unidades, "", new { @class = "text-danger" })

                </div>
            </div>
            <div class="form-group">

                <label class="control-label col-md-4" for="resultado">Límite de Detección: </label>
                <div class="col-md-7">
                    @Html.EditorFor(model => model.limite_deteccion, new { htmlAttributes = new { @class = "form-control", @Value = @analisis.limites } })
                    @Html.ValidationMessageFor(model => model.limite_deteccion, "", new { @class = "text-danger" })
                    @*<input type="text" name="deteccion" value="@analisis.limites" class="form-control" />
                    @Html.ValidationMessageFor(model => model.limite_deteccion, "", new { @class = "text-danger" })*@
                </div>
            </div>
                <div class="form-group">
                    <label class="control-label col-md-4" for="resultado">Método: </label>
                    <div class="col-md-7">
                        <input type="text" name="metodo" value="@analisis.metodo" class="form-control" />
                        @Html.ValidationMessageFor(model => model.metodo, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-4" for="comentario">Comentarios: </label>
                    <div class="col-md-7">
                        <input type="text" name="comentario" value="" class="form-control" />
                        @Html.ValidationMessageFor(model => model.comentario, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <div class="col-md-6 hide" id="alert">
                            <div class="alert alert-success" role="alert" id="alertMsg"></div>
                        </div>
                        <div class="col-md-5 pull-right">
                            <button type="submit" class="btn btn-success" onclick="cambiarComas()" id="guardar">Guardar</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </div>
        }
    </div>
</div>

Views/Reporte/Editar.cshtml
@model LaboratorioMarn.REPORTE
@{
    DETALLE_SOLICITUD detalleSolicitud = ViewBag.DetalleSol;
    REPORTE reporte = ViewBag.Reporte;
    
}
<div class="row">
    <div class="col-sm-12">
        @using (Html.BeginForm("Edit", "Reporte", FormMethod.Post, htmlAttributes: new { @id = "formularioEditarReporte", @class = "form-horizontal" }))
        {
            <input type="hidden" name="idReporte" value="@reporte.id_reporte" />
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.id_reporte)


            <script type="text/javascript">
                function sumar() {
                    var resultado = document.getElementById('resultado').value;
                    var incerteza = document.getElementById('incerteza').value;

                    incerteza *= resultado;
                    document.getElementById('incerteza').value = incerteza;
                }
            </script>

            <div class="form-group">
                <label class="control-label col-md-4" for="resultado">Análisis: </label>
                <label class="control-label col-md-7" style="text-align: center" for="resultado">@detalleSolicitud.ANALISI.nombre</label>
                @Html.HiddenFor(model => model.id_analisis_empleado)
            </div>
            <div class="form-group">
                <label class="control-label col-md-4" for="resultado">Resultado: </label>
                <div class="col-md-7">
                    <input type="text" name="resultado" id="resultado" value="@Model.resultado" onchange="sumar();" class="form-control" />
                    @*@Html.EditorFor(model => model.resultado, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.resultado, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-4" for="resultado">Incerteza: </label>
                <div class="col-md-7">
                    <input type="text" name="incerteza" id="incerteza" value="@Model.incerteza" class="form-control"  />
                    @*@Html.EditorFor(model => model.incerteza, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.incerteza, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-4" for="resultado">Unidades: </label>
                <div class="col-md-7">
                    @Html.EditorFor(model => model.unidades, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.unidades, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-4" for="resultado">Límite de Detección: </label>
                <div class="col-md-7">
                    @*<input type="text" name="deteccion" id="deteccion" value="@Model.limite_deteccion" class="form-control" />*@
                    @Html.EditorFor(model => model.limite_deteccion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.limite_deteccion, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-4" for="resultado">Método: </label>
                <div class="col-md-7">
                    @Html.EditorFor(model => model.metodo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.metodo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-4" for="comentario">Comentarios: </label>
                <div class="col-md-7">
                    @Html.EditorFor(model => model.comentario, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.comentario, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <div class="col-md-6 hide" id="alert">
                        <div class="alert alert-success" role="alert" id="alertMsg"></div>
                    </div>
                    <div class="col-md-5 pull-right">
                        <button type="submit" class="btn btn-success" onclick="cambiarComas()" id="guardar">Guardar</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Views/Reporte/Get.cshtml
@model IEnumerable<LaboratorioMarn.REPORTE>

@{
    PROCESO_ANALISTA procesoAnalista = ViewBag.procesoAnalista;
}

<h4>Empleado: @ViewBag.empleado.nombre_empleado</h4>

@if (procesoAnalista.id_estado_proceso_analista == 4)
{ 
    <p class="bg-info">Este reporte ya fue aprobado.</p>
}

<table class="table table-condensed table-striped table-bordered">
    <tr>
        <th>
            Análisis
        </th>
        <th>
            Resultado
        </th>
        <th>
            Incertezas
        </th>
        <th>
            Unidades
        </th>
        <th>
            Límite de Detección
        </th>
        <th>
            Método
        </th>
        <th>
            Comentario
        </th>
    </tr>
    @foreach (REPORTE reporte in Model)
    {
        <tr>
            <td>
                @reporte.ANALISIS_EMPLEADO.DETALLE_SOLICITUD.ANALISI.nombre
            </td>
            <td>
                @reporte.resultado
            </td>
            <td>
                @reporte.incerteza
            </td>
            <td>
                @reporte.unidades
            </td>
            <td>
                @reporte.limite_deteccion
            </td>
            <td>
                @reporte.metodo
            </td>
            <td>
                @reporte.comentario
            </td>
        </tr>
    }
</table>

<div class="row">
    <div class="col-md-8">
        <div class="col-md-12 hide" id="alert">
            <div class="alert alert-success" role="alert" id="alertMsg"></div>
        </div>
    </div>
    @if (procesoAnalista.id_estado_proceso_analista != 6)
    { 
        <div class="col-md-4">
            @if (procesoAnalista.id_estado_proceso_analista == 3)
            { 
                <a href="#" class="accionResultado btn btn-success" data-accion="aprobar">Aprobar</a>
            }

            <a href="#" class="accionResultado btn btn-danger" data-accion="denegar">Denegar</a>
        </div>
    }
</div>